favicon: null
name: i2e
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7791838340926915
  brandStrength: 0.4849196742288768
  lightness: 0.9106327618937939
  brandColors:
    - '#0B5487'
    - '#0E70B3'
    - '#FBFFFF'
    - '#B8C3C6'
    - '#66889B'
  rhythmicContrast: 0.7722560937982053
typography_spectrum: 0.00119824125431478
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.09401818225160241
analytics:
  twitter: null
  google: null
  facebook: null
