name: i2e
favicon: null
layout_spectrum: 0.09401818225160241
typography_spectrum: 0.0011982412543147802
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.48491967422887683
  lightness: 0.9106327618937939
  saturation: 0.7791838340926915
  rhythmicContrast: 0.7722560937982053
purpose: []
